#ifndef CONFIG_H
#define CONFIG_H

#define LIMIARFRENTE 1000
#define LIMIARDIAGONAIS 750
#define LIMIARLATERAIS 500
#define LIMITELEITURA 5000
#define VELOCIDADEROTACAO 15 //50
#define VELOCIDADEDESLOCAMENTO 50 //400

//Logs
#define LOG                false
#define INFO_WALL_FOLLOWER false

#endif // CONFIG_H
